---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Install GPG
      apt:
        name: gpg-agent
        update_cache: true
        state: present
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include j91321.kibana"
      include_role:
        name: "j91321.kibana"
