---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Kibana is running
    uri:
      url: http://127.0.0.1:5601
      status_code: 503
    register: result
    until: result.status == 503
    retries: 60
    delay: 1
